<?php

namespace app\models;

use app\models\schema\History as HistorySchema;
use yii\helpers\Json;

class History extends HistorySchema
{
    /** @var array */
    private $detailJsonDecode;

    public function afterFind()
    {
        $this->detailJsonDecode = Json::decode($this->detail);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function getDetailData($attribute): array
    {
        return $this->detailJsonDecode['data'][$attribute] ?? [];
    }

    public function getDetailChangedAttribute($attribute): array
    {
        return $this->detailJsonDecode['changedAttributes'][$attribute] ?? [];
    }

    public function getDetailOldValue($attribute): ?string
    {
        return $this->getDetailChangedAttribute($attribute)['old'] ?? null;
    }

    public function getDetailNewValue($attribute): ?string
    {
        return $this->getDetailChangedAttribute($attribute)['new'] ?? null;
    }

    public function getEventText(): string
    {
        return static::getEventTextByEvent($this->event);
    }
}
